---
### Notify Alarm Status change
- id: '1586327112617'
  alias: Notify Alarm Armed Home
  description: Notify when Alarm panel is armed Home
  trigger:
  - entity_id: alarm_control_panel.home_alarm
    platform: state
  condition: []
  action:
  - data:
      message: Home alarm {{ states.alarm_control_panel.home_alarm.state }}
      title: Home Alarm
    service: notify.mobile_app_mi_9t
  - data:
      message: Home alarm {{ states.alarm_control_panel.home_alarm.state }}
      title: Home Alarm
    service: notify.mobile_app_nokia_6_1