decluttering_templates:
  automation_template:
    card:
      card:
        show_header_toggle: false
        title: '[[name]] automations'
        type: entities
      filter:
        include:
          - entity_id: 'automation.[[slug]]*'
      sort: entity_id
      type: 'custom:auto-entities'
title: Home
views:
  - badges:
      - entity: person.david
      - entity: person.karen
      - entity: sensor.home_alarm_keypad
      - entity: sensor.south_africa_coronavirus_deaths
      - entity: sensor.south_africa_coronavirus_confirmed
      - entity: sensor.south_africa_coronavirus_recovered
      - entity: sun.sun
    cards:
      - entity: alarm_control_panel.home_alarm
        type: alarm-panel
      - card:
          show_header_toggle: false
          title: Open Doors/Windows
          type: entities
        filter:
          exclude:
            - name: '*Pet*'
            - state: 'off'
          include:
            - name: '*Door*'
            - name: '*Window*'
        show_empty: false
        type: 'custom:auto-entities'
      - entities:
          - entity: light.kitchen_led_1
        title: Lights
        type: entities
      - entity: weather.home
        type: weather-forecast
      - entities:
          - entity: binary_sensor.hub_home_hub
          - entity: binary_sensor.pet_flap_kitchen_pet_door_connectivity
          - entity: sensor.pet_flap_kitchen_pet_door
          - entity: binary_sensor.pet_jessie
          - entity: binary_sensor.pet_ziva
          - entity: sensor.jessie_trips_outside_today
          - entity: sensor.ziva_trips_outside_today
          - entity: sensor.jessie_outside_time_today
          - entity: sensor.ziva_outside_time_today
        title: Sure Flap Status
        type: entities
      - aspect_ratio: 0%
        camera_image: camera.front_camera
        camera_view: live
        entities:
          - entity: camera.front_camera
        title: Front Camera
        type: picture-glance
      - aspect_ratio: 0%
        camera_image: camera.back_camera
        camera_view: live
        entities:
          - entity: camera.back_camera
        title: Back Camera
        type: picture-glance
      - entities:
          - entity: sensor.temperature_158d0002011a32
          - entity: sensor.temperature_158d00020ec6bf
          - entity: sensor.temperature_158d0001f54c03
          - entity: sensor.temperature_158d0001fa5057
          - entity: sensor.temperature_158d00020177c3
          - entity: sensor.temperature_158d00023475b0
          - entity: sensor.humidity_158d00023475b0
        title: Temperature and Humidity
        type: entities
      - card:
          show_header_toggle: false
          title: Battery level <20%
          type: entities
        filter:
          exclude:
            - name: Mi 9T*
            - name: '*Nokia*'
            - name: Humidity*
          include:
            - name: '*Battery*'
              state: < 20
        show_empty: false
        type: 'custom:auto-entities'
    path: default_view
    title: Home
