---
#-
#  _ _       _     _
# | (_) __ _| |__ | |_ ___
# | | |/ _` | '_ \| __/ __|
# | | | (_| | | | | |_\__ \
# |_|_|\__, |_| |_|\__|___/
#      |___/
#
#- from github.com/tinuva/home-assistant-config
- platform: mqtt
  name: "Kitchen Led #1"
  state_topic: "stat/kitchen-led1/POWER"
  command_topic: "cmnd/kitchen-led1/power"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  retain: false