binary_sensor:
  platform: template
  sensors:
    both_parent_phones_charging:
      friendly_name: "Is both parents phones charging"
      value_template: >-
        {{ (is_state('sensor.mi_9t_battery_state', 'charging')
          or is_state('sensor.mi_9t_battery_state', 'not_charging')) 
          and is_state('sensor.nokia_6_1_battery_state', 'charging') }}
      # silly workaround needed - mi9t phone shows not_charging when in fact charging...

automation:
  - alias: Parents both in bed when both phones charge
    description: Parents both in bed when both phones charge
    trigger:
    - entity_id: binary_sensor.both_parent_phones_charging
      platform: state
      to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.both_parent_phones_charging
        state: 'on'
      - condition: state  # 'night' condition: from sunset until sunrise 
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: disarmed
    action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.home_alarm
