binary_sensor:
  - platform: template
    sensors:
      surepet_battery_no_activity:
        value_template: >
          {{ (now().timestamp() - as_timestamp(states.sensor.pet_flap_kitchen_pet_door_battery_level.last_updated)) | int //60 > 1260 }}

automation:
- id: surepet_sensor_warning_test
  alias: Surepet Battery Sensor Warning Test
  trigger:
  - entity_id: sensor.surepet_battery_no_activity
    platform: state
    to: 'on'
  action:
  - service: notify.slack
    data_template:
      title: Sensor-Warning!
      target: ["#alerts"]
      message: >
        Surepet Flap Battery Sensor has not been updated for 1260 Minutes!
      data:
        icon: ":dog2:"
        username: "Pet Alerts"
        blocks_template:
          - type: section
            text:
              type: mrkdwn
              text: >
                Surepet Flap Battery Sensor has not been updated for 1260 Minutes!