automation:
  - alias: "Turn on Babyroom Heater"
    trigger:
      - platform: state
        entity_id: sensor.temperature_158d0001fa5057, sensor.temperature_158d0002011a32   # baby room, outside
    condition:
      - condition: template # temp below 20.4
        value_template: "{{ (states.sensor.temperature_158d0001fa5057.state|float < 20.4) and (states.sensor.temperature_158d0002011a32.state|float < states.sensor.temperature_158d0001fa5057.state|float)}}"
    action:
      - service: switch.turn_on
        entity_id: switch.heater_baby_room

  - alias: "Turn off Babyroom Heater"
    trigger:
      - platform: state
        entity_id: sensor.temperature_158d0001fa5057, sensor.temperature_158d0002011a32   # baby room, outside
      - platform: time_pattern
        # You can also match on interval. This will match every 5 minutes
        minutes: "/5"
    condition:
      - condition: template # temp below 20.4
        value_template: "{{ ((states.sensor.temperature_158d0001fa5057.state|float > 20.5) or (states.sensor.temperature_158d0002011a32.state|float > states.sensor.temperature_158d0001fa5057.state|float)) }}"
    action:
      - service: switch.turn_off
        entity_id: switch.heater_baby_room