---
#-
#
#  _______  _ __   ___  ___
# |_  / _ \| '_ \ / _ \/ __|
#  / / (_) | | | |  __/\__ \
# /___\___/|_| |_|\___||___/
#
#
#- from github.com/tinuva/home-assistant-config
zone:
  - name: Home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 50
    icon: mdi:home
  
  - name: Work
    latitude: !secret latitude_work
    longitude: !secret longitude_work
    radius: 310
    icon: mdi:work
  
  - name: Curro Rosen Castle
    latitude: !secret latitude_currorosencastle
    longitude: !secret longitude_currorosencastle
    radius: 110
    icon: mdi:map-marker

# David = device_tracker.mi_9t
# Karen = device_tracker.nokia_6_1

automation:
  - alias: Parent arrived at School
    description: Parent arrived at School
    trigger:
    - entity_id: device_tracker.mi_9t
      platform: state
      to: 'Curro Rosen Castle'
    - entity_id: device_tracker.nokia_6_1
      platform: state
      to: 'Curro Rosen Castle'
    action:
    - service: notify.slack
      data_template:
        target: ["#general"]
        message: >
          {% if (states.device_tracker.mi_9t.state == "Curro Rosen Castle") %}David{% endif %}
          {% if (states.device_tracker.nokia_6_1.state == "Curro Rosen Castle") %}Karen{% endif %}
          arrived at Curro Rosen Castle

  - alias: Parent left School
    description: Parent left School
    trigger:
    - entity_id: device_tracker.mi_9t
      platform: state
      from: 'Curro Rosen Castle'
    - entity_id: device_tracker.nokia_6_1
      platform: state
      from: 'Curro Rosen Castle'
    action:
    - service: notify.slack
      data_template:
        target: ["#general"]
        message: >
          {% if (trigger.from_state.object_id == 'device_tracker.mi_9t') %}David{% endif %}
          {% if (trigger.from_state.object_id == 'device_tracker.nokia_6_1' ) %}Karen{% endif %}
          {{ trigger.to_state.object_id }}
          left Curro Rosen Castle
          {{ trigger.from_state.object_id }}